---
:concurrency: 2
staging:
  :concurrency: 2
production:
  :concurrency: 2
:queues:
  - [paperclip, 2] # More weight since image processing happens frequently
  - notifications # For mails and push notifications
  - default # For geocoding and newsletter